version: '3.8'

services:

  interngram-app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        WORKDIR: ${WORKING_DIR}
    networks:
      - local
    depends_on:
      - interngram-db
    env_file:
      - ".env"
    expose:
      - "8080"
    ports:
      - "8080:8080"

  interngram--pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - local

  interngram-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  local:
